# Generated by Django 5.0.3 on 2024-03-12 15:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_brand_branches'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(help_text='Enter a valid phone number. Up to 11 digits allowed.', max_length=11, null=True, validators=[django.core.validators.RegexValidator('^(?:\\+20|0)?1\\d{9}$')]),
        ),
    ]
